//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingEcommerce.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public string FooterID { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
